{{ $root := . }}
apiVersion: v1
items:
{{- range $key, $value := .Values.projects }}
- apiVersion: authorization.openshift.io/v1
  groupNames: null
  kind: RoleBinding
  metadata:
    creationTimestamp: null
    name: system:deployers
    namespace: {{ $key }}
  roleRef:
    name: system:deployer
  subjects:
  - kind: ServiceAccount
    name: deployer
    namespace: {{ $key }}
  userNames:
  - system:serviceaccount:{{ $key }}:deployer
- apiVersion: authorization.openshift.io/v1
  groupNames: null
  kind: RoleBinding
  metadata:
    creationTimestamp: null
    name: system:image-builders
    namespace: {{ $key }}
  roleRef:
    name: system:image-builder
  subjects:
  - kind: ServiceAccount
    name: builder
    namespace: {{ $key }}
  userNames:
  - system:serviceaccount:{{ $key }}:builder
- apiVersion: authorization.openshift.io/v1
  groupNames:
  - system:serviceaccounts:{{ $key }}
  kind: RoleBinding
  metadata:
    creationTimestamp: null
    name: system:image-pullers
    namespace: {{ $key }}
  roleRef:
    name: system:image-puller
  subjects:
  - kind: SystemGroup
    name: system:serviceaccounts:{{ $key }}
  userNames: null
{{- end }}
kind: List
